### ISSUE TITLE
Coords. (Lat-Long) disabled

### ISSUE THREAD

**Issue by csalamade** [mgp25/Probe-Hunter#4]
I was able to start the program but could not connect to wigle.
Can you provide a more detailed guide on how to edit the wigle.py file? Because I tried it but it didn’t come together

**Comment by mgp25** [comment]
You only need to edit the `AUTH` var from [wigle.py](https://github.com/mgp25/Probe-Hunter/blob/master/wigle.py)

Regards

**Comment by csalamade** [comment]
we have the error. The word "basic" was missing.

**Comment by mgp25** [comment]
You need to provide the whole token with `Basic` as shown in the Wigle page....

Example: `Basic <your token>`
